#!/bin/bash
#SBATCH --account=rpp-jillings
#SBATCH --time=00:40:00
#SBATCH --job-name=psterile884
#SBATCH --error=/home/fatemigh/projects/rpp-jillings/fatemigh/sterile/Likelihood/%x-%j.err
source  /home/fatemigh/projects/rpp-jillings/fatemigh/env.sh
root -b -q '/home/fatemigh/projects/rpp-jillings/fatemigh/sterile/Likelihood/LikelihoodSterile_modified7.C+(884)'