#!/bin/bash
#SBATCH --job-name=python/pythonoutputsterilegamma88
#SBATCH --error=/home/fatemigh/projects/rpp-jillings/fatemigh/sterile/Likelihood/%x-%j.err
#SBATCH --account=rpp-jillings
#SBATCH --time=00:10:00
source  /home/fatemigh/projects/rpp-jillings/fatemigh/env.sh
root -b -q '/home/fatemigh/projects/rpp-jillings/fatemigh/sterile/Likelihood/LikelihoodSterile_modified5.C+(88)'