#!/bin/bash
#SBATCH --job-name=python/pythonoutputsterilegamma160
#SBATCH --account=rpp-jillings
#SBATCH --time=00:10:00
#SBATCH --mem-per-cpu=3024M
source  /home/fatemigh/projects/rpp-jillings/fatemigh/env.sh
root -b -q '/home/fatemigh/projects/rpp-jillings/fatemigh/sterile/Likelihood/LikelihoodSterile_modified5.C+(160)'